### PR TITLE
NetCDF visualization tools in Docker

### PR DESCRIPTION
**Pull request by craig-willis**
Added netcdf-xpra Docker image with support for https://github.com/terraref/computing-pipeline/issues/340:
* xpra + openbox (lightweight desktop)
* panoply, ncview
* NCO development dependencies

### CODE REVIEW

**Comment by craig-willis** [comment]
@hmb1  
Please have a look at the Dockerfile and let me know if there are any other tools/dependencies that would be helpful.  This should have the full NCO development stack from our earlier exchange along with Panoply and NCView.

**Comment by hmb1** [comment]
Hi Craig,
 is it in the ndslabs.org catalogue - can I try before you commit -just so there are no mistakes ?
...Henry

**Comment by craig-willis** [comment]
You can test by just restarting the existing Panoply/Xpra service in workbench. This should give you the latest image with the nco dependencies and ncview.

**Comment by hmb1** [comment]
OK just checked NCO, ncview, Panoply all working OK

**Comment by craig-willis** [comment]
Great, thanks.  I'll go ahead and merge this and add it to the catalog.  If you ever need other tools for hyperspectral, we can easily add them to this image.

**Pull request merged**
